### ISSUE TITLE
Allow array as presenter mapping

### ISSUE THREAD

**Issue by enumag** [nette/application#101]
The [PresenterFactory](https://github.com/nette/application/blob/master/src/Application/PresenterFactory.php#L19-L22) splits the mapping mask to 3 parts - a prefix, a part which is reapeated for each module and a part for presenter. The problem is that there is no way to actually configure the 3 parts separately. In my case I need the mapping to look like this:

```
'*' => array('App\', 'Module\*Module\', 'Presenter\*Presenter')
```

This is currently not possible to achieve. I tried the following:

```
nette.application:
    mapping:
        *: App\Module\*Module\Presenter\*Presenter
# result:
# '*' => array('App\Module\', '*Module\', 'Presenter\*Presenter')
```

```
nette.application:
    mapping:
        *: App\*Module\Module\Presenter\*Presenter
# result:
# '*' => array('App\', '*Module\', 'Module\Presenter\*Presenter')
```

To achieve the mapping I want I'd have to create my own PresenterFactory. And I can't even extend the default one because the mapping property is private (don't want to hack it using reflection).

Instead I'd like the PresenterFactory to accept an array as well so that this would work:

```
nette.application:
	mapping:
		*: [ App\, Module\*Module\, Presenter\*Presenter ]
```

**Comment by JanTvrdik** [comment]
:+1:

**Comment by Majkl578** [comment]
:-1: It's even more obscure than current syntax. :(

**Comment by fprochazka** [comment]
I think it should be objects, then you would register

```yml
nette.application:
    mapping:
        *: Nette\Application\PresenterMapping("App\\", "Module\\*Module\\", "Presenter\\*Presenter")
        Custom: My\Custom\PresenterMapping()
        VeryCustom: @My\Custom\PresenterMapping() # find service in container
```

ofcourse, the default syntax could string for the `Nette\Application\PresenterMapping` due to compatibility, so you'd get

```yml
nette.application:
    mapping:
        *: App\Module\*Module\Presenter\*Presenter
        Custom: My\Custom\PresenterMapping()
        VeryCustom: @My\Custom\PresenterMapping() # find service in container
```

and ofcourse, you'd have to implement an interface

```php
class IPresenterMapping {
    public function formatPresenterClass($presenter);
    public function unformatPresenterClass($class);
}
```

Then PresenterFactory's only job would be to find the namespace in array and call the method.
