### ISSUE TITLE
Setting templateClass doesn't work

### ISSUE THREAD

**Issue by diegosardina** [nette/application#284]
To temporary workaround this #283, I'm forcing the type of the factory class to be of Nette\Bridges\ApplicationLatte\TemplateFactory.

```
latte:
      	templateClass: App\JustTestTemplate
services:
       latte.templateFactory:
               class: Nette\Bridges\ApplicationLatte\TemplateFactory

```

However, setting templateClass in latte section doesn't change the class that templateFactory is going to create.

It works without specifying that class in latte.templateFactory.
